### ISSUE TITLE
Secret Key Size / Value

### ISSUE THREAD

**Issue by kirk-baird** [sigp/milagro_bls#18]
Secret Key should be between values `1 < sk < r - 1` as defined [here](https://tools.ietf.org/html/draft-boneh-bls-signature-00#section-2.2), where `r` is a little less than 32 bytes.
This check should be added to `from_bytes()` .
Furthermore we should also then change `SecretKey.x` to private to prevent modification to the secret key to be larger than `r`.

This could also be a good time to change `SecretKey::from_bytes()` to take a bytes which are less than 48 bytes. I would recommend allowing any bytes less than 48 bytes and appending the necessary number of zero bytes such the input length is 48 bytes and can be deserialised using the `Big::frombytes()` function.

**Comment by paulhauner** [comment]
This all sounds good to me!

**Comment by kirk-baird** [comment]
Slight change the range should be inclusive of 1 and r - 1:
`1 <= sk <= r - 1`
