### ISSUE TITLE
Check the input of SecretKey.from_bytes to be non zero

### ISSUE THREAD

**Issue by ChihChengLiang** [sigp/milagro_bls#39]
Hi @kirk-baird, 

In the recent release, the standard disallows zero secret key. Should we also add a non-zero check in the SecretKey.from_bytes method? Or do we intentionally don't do so?

https://github.com/sigp/milagro_bls/blob/515201c5d165f1e08bca93e24cad4044eeed6e21/src/keys.rs#L73-L77

**Comment by kirk-baird** [comment]
Thanks that's a good point you raise we should reject `SecretKey::from_bytes([0; 32])`. I'll add that in now and make another release :)

**Comment by ChihChengLiang** [comment]
Thank you so much Kirk!

**Comment by kirk-baird** [comment]
I'll make a release when this one gets merged upstream https://github.com/apache/incubator-milagro-crypto-rust/pull/47

**Comment by kirk-baird** [comment]
Resolved in #41
