### ISSUE TITLE
Check that IKM is > 32B in KeyGen

### ISSUE THREAD

**Issue by veorq** [sigp/milagro_bls#45]
IKM should be checked to be at least 32 bytes in 

https://github.com/sigp/milagro_bls/blob/c5e6c5e2dc0b9ca757b90141b807683ce98aac23/src/keys.rs#L42-L45

as per https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-04#section-2.3.

**Comment by kirk-baird** [comment]
Yep, you're correct. 

Sorry about the excessively slow reply this repo isn't used very often anymore. I'll make a PR to update that.
