### ISSUE TITLE
Broken link for milagro

### ISSUE THREAD

**Issue by prestonvanloon** [sigp/milagro_bls#8]
This is the link in the README, but it's a 404: https://github.com/milagro-crypto/amcl

**Comment by kirk-baird** [comment]
You're right thanks, seems that the library has moved. I'll try track down where it has moved too.

**Comment by prestonvanloon** [comment]
Thanks! I was struggling to find it as well

**Comment by paulhauner** [comment]
Turns out the maintainers were in the middle of a re-shuffle.

The new repo (as of 16hrs ago) is here: https://github.com/apache/incubator-milagro-crypto-rust
